# Generated by Django 4.2.3 on 2023-11-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=150)),
                ('qanak', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('photo', models.ImageField(upload_to='photos')),
                ('tort_info', models.TextField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cakesapp.category')),
            ],
        ),
    ]
